import = [
  "~/.config/alacritty/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMonoNL Nerd Font Mono"

size = 12


